import React, { useState } from 'react';

const itemsData = [
    { name: 'Battle Trance', type: 'Amulet', monsters: 'none', dungeon: 'none' },
    { name: 'Deathspeaker\'s Pendant', type: 'Amulet', monsters: 'none', dungeon: 'none' },
    { name: 'Word of Kahan', type: 'Amulet', monsters: 'none', dungeon: 'none' },
    { name: 'Esadora\'s Overflowing Cameo', type: 'Amulet', monsters: 'none', dungeon: 'none'},
    { name: 'Melted Heart of Selig', type: 'Amulet', monsters: 'none', dungeon: 'none'},
    { name: 'Ancient\'s Oath', type: '2H Axe', monsters: 'Cannibals, Goatmen', dungeon: 'Bastion of Faith, Bloodsoaked Crag, Charnel House, Earthen Wound (NMD), Faceless Shrine, Guulrahn Slums (NMD), Pallid Delve, Steadfast Barracks. Anica\'s Claim, Broken Bulwark, Champion\'s Demise (NMD), Domhainne Tunnels, Forsaken Quarry, Hoarfrost Demise, Komdor Temple, Mercy\'s Reach, Oldstones, Rimescar Caverns, Sepulcher of the Forsworn, Shivta Ruins(NMD)'},
    { name: 'Waxing Gibbous', type: '1H Axe', monsters: 'Cannibals, Fallen, Goatmen', dungeon: 'Bastion of Faith, Bloodsoaked Crag, Charnel House, Earthen Wound (NMD), Faceless Shrine, Guulrahn Slums (NMD), Pallid Delve, Steadfast Barracks, Ancient\'s Lament (NMD), Demon\'s Wake (NMD), Fading Echo, Grinning Labyrinth, Oblivion, Ruinds of Eridu, Wretched Delve, Anica\'s Claim, Broken Bulwark, Champion\'s Demise (NMD), Domhainne Tunnels, Forsaken Quarry, Hoarfrost Demise, Komdor Temple, Mercy\'s Reach, Oldstones, Rimescar Caverns, Sepulcher of the Forsworn, Shivta Ruins(NMD)'},
    { name: 'Butcher\'s Cleaver', type: '1H Axe', monsters: 'Cannibals, Fallen, Goatmen', dungeon: 'Bastion of Faith, Bloodsoaked Crag, Charnel House, Earthen Wound (NMD), Faceless Shrine, Guulrahn Slums (NMD), Pallid Delve, Steadfast Barracks, Ancient\'s Lament (NMD), Demon\'s Wake (NMD), Fading Echo, Grinning Labyrinth, Oblivion, Ruinds of Eridu, Wretched Delve, Anica\'s Claim, Broken Bulwark, Champion\'s Demise (NMD), Domhainne Tunnels, Forsaken Quarry, Hoarfrost Demise, Komdor Temple, Mercy\'s Reach, Oldstones, Rimescar Caverns, Sepulcher of the Forsworn, Shivta Ruins(NMD)'},
    { name: '100,000 Steps', type: 'Boots', monsters: 'Drowned', dungeon: 'Akkhan\'s Grasp, Belfry Zakara, Corrupted Grotto, Dead Man\'s Dredge, Fetid Mausoleum, Flooded Depths, Ghoa Ruins, Haunted Refuge, Mariner\'s Refuge, Putrid Aquifer, Ruinds of Eridu, Sunken Library, Vault of the Forsaken'},
    { name: 'Greaves of the Empty Tomb', type: 'Boots', monsters: 'Drowned', dungeon: 'Akkhan\'s Grasp, Belfry Zakara, Corrupted Grotto, Dead Man\'s Dredge, Fetid Mausoleum, Flooded Depths, Ghoa Ruins, Haunted Refuge, Mariner\'s Refuge, Putrid Aquifer, Ruinds of Eridu, Sunken Library, Vault of the Forsaken'},
    { name: 'Esu\'s Heirloom', type: 'Boots', monsters: 'Drowned', dungeon: 'Akkhan\'s Grasp, Belfry Zakara, Corrupted Grotto, Dead Man\'s Dredge, Fetid Mausoleum, Flooded Depths, Ghoa Ruins, Haunted Refuge, Mariner\'s Refuge, Putrid Aquifer, Ruinds of Eridu, Sunken Library, Vault of the Forsaken'},
    { name: 'Penitent Greaves', type: 'Boots', monsters: 'Drowned', dungeon: 'Akkhan\'s Grasp, Belfry Zakara, Corrupted Grotto, Dead Man\'s Dredge, Fetid Mausoleum, Flooded Depths, Ghoa Ruins, Haunted Refuge, Mariner\'s Refuge, Putrid Aquifer, Ruinds of Eridu, Sunken Library, Vault of the Forsaken'},
    { name: 'Skyhunter', type: 'Bow', monsters: 'Ghost, Vampires', dungeon: 'Abandoned Mineworks (NMD), Black Asylum (NMD), Broken Bulwark, Buried Halls, Calibel\'s Mine, Crumbling Hekma, Earthen Wound (NMD), Forbidden City, Guulrahn Slums (NMD), Halls of the Damned, Haunted Refuge, Immortal Emanation, Iron Hold, Lost Archives (NMD), Lost Keep, Maddux Watch, Mariner\'s Refuge, Oblivion, Onyx Hold (NMD), Penitent Cairns, Sealed Archives, Seaside Descent, Stockades, Sunken Ruins (NMD), Tomb of the Saints, Twisted Hollow, Whispering Vault (NMD), Akkhan\'s Grasp, Collapsed Vault, Dead Man\'s Dredge, Fetid Mausoleum, Forbidden City, Hallowed Ossuary, Heathen\'s keep, Immortal Emanation, Kor Dragan Barracks (NMD), Sanguine Chapel, Zenith (NMD)'},
    { name: 'Windforce', type: 'Bow', monsters: 'Ghost, Vampires', dungeon: 'Abandoned Mineworks (NMD), Black Asylum (NMD), Broken Bulwark, Buried Halls, Calibel\'s Mine, Crumbling Hekma, Earthen Wound (NMD), Forbidden City, Guulrahn Slums (NMD), Halls of the Damned, Haunted Refuge, Immortal Emanation, Iron Hold, Lost Archives (NMD), Lost Keep, Maddux Watch, Mariner\'s Refuge, Oblivion, Onyx Hold (NMD), Penitent Cairns, Sealed Archives, Seaside Descent, Stockades, Sunken Ruins (NMD), Tomb of the Saints, Twisted Hollow, Whispering Vault (NMD), Akkhan\'s Grasp, Collapsed Vault, Dead Man\'s Dredge, Fetid Mausoleum, Forbidden City, Hallowed Ossuary, Heathen\'s keep, Immortal Emanation, Kor Dragan Barracks (NMD), Sanguine Chapel, Zenith (NMD)'},
    { name: 'Rage of Harrogath', type: 'Chest', monsters: 'Beast, Spiders', dungeon: 'Abandoned Mineworks (NMD), Black Asylum (NMD), Broken Bulwark, Buried Halls, Calibel\'s Mine, Crumbling Hekma, Earthen Wound (NMD), Forbidden City, Guulrahn Slums (NMD), Halls of the Damned, Haunted Refuge, Immortal Emanation, Iron Hold, Lost Archives (NMD), Lost Keep, Maddux Watch, Mariner\'s Refuge, Oblivion, Onyx Hold (NMD), Penitent Cairns, Sealed Archives, Seaside Descent, Stockades, Sunken Ruins (NMD), Tomb of the Saints, Twisted Hollow, Whispering Vault (NMD), Akkhan\'s Grasp, Collapsed Vault, Dead Man\'s Dredge, Fetid Mausoleum, Forbidden City, Hallowed Ossuary, Heathen\'s keep, Immortal Emanation, Kor Dragan Barracks (NMD), Sanguine Chapel, Zenith (NMD)' },
    { name: 'Insatiable Fury', type: 'Chest', monsters: 'Beast, Spiders', dungeon: 'Abandoned Mineworks (NMD), Black Asylum (NMD), Broken Bulwark, Buried Halls, Calibel\'s Mine, Crumbling Hekma, Earthen Wound (NMD), Forbidden City, Guulrahn Slums (NMD), Halls of the Damned, Haunted Refuge, Immortal Emanation, Iron Hold, Lost Archives (NMD), Lost Keep, Maddux Watch, Mariner\'s Refuge, Oblivion, Onyx Hold (NMD), Penitent Cairns, Sealed Archives, Seaside Descent, Stockades, Sunken Ruins (NMD), Tomb of the Saints, Twisted Hollow, Whispering Vault (NMD), Akkhan\'s Grasp, Collapsed Vault, Dead Man\'s Dredge, Fetid Mausoleum, Forbidden City, Hallowed Ossuary, Heathen\'s keep, Immortal Emanation, Kor Dragan Barracks (NMD), Sanguine Chapel, Zenith (NMD)' },
    { name: 'Mad Wolf\'s Glee', type: 'Chest', monsters: 'Beast, Spiders', dungeon: 'Abandoned Mineworks (NMD), Black Asylum (NMD), Broken Bulwark, Buried Halls, Calibel\'s Mine, Crumbling Hekma, Earthen Wound (NMD), Forbidden City, Guulrahn Slums (NMD), Halls of the Damned, Haunted Refuge, Immortal Emanation, Iron Hold, Lost Archives (NMD), Lost Keep, Maddux Watch, Mariner\'s Refuge, Oblivion, Onyx Hold (NMD), Penitent Cairns, Sealed Archives, Seaside Descent, Stockades, Sunken Ruins (NMD), Tomb of the Saints, Twisted Hollow, Whispering Vault (NMD), Akkhan\'s Grasp, Collapsed Vault, Dead Man\'s Dredge, Fetid Mausoleum, Forbidden City, Hallowed Ossuary, Heathen\'s keep, Immortal Emanation, Kor Dragan Barracks (NMD), Sanguine Chapel, Zenith (NMD)' },
    { name: 'Blood Artisan\'s Cuirass', type: 'Chest', monsters: 'Beast, Spiders', dungeon: 'Abandoned Mineworks (NMD), Black Asylum (NMD), Broken Bulwark, Buried Halls, Calibel\'s Mine, Crumbling Hekma, Earthen Wound (NMD), Forbidden City, Guulrahn Slums (NMD), Halls of the Damned, Haunted Refuge, Immortal Emanation, Iron Hold, Lost Archives (NMD), Lost Keep, Maddux Watch, Mariner\'s Refuge, Oblivion, Onyx Hold (NMD), Penitent Cairns, Sealed Archives, Seaside Descent, Stockades, Sunken Ruins (NMD), Tomb of the Saints, Twisted Hollow, Whispering Vault (NMD), Akkhan\'s Grasp, Collapsed Vault, Dead Man\'s Dredge, Fetid Mausoleum, Forbidden City, Hallowed Ossuary, Heathen\'s keep, Immortal Emanation, Kor Dragan Barracks (NMD), Sanguine Chapel, Zenith (NMD)' },
    { name: 'Raiment of the Infinite', type: 'Chest', monsters: 'Beast, Spiders', dungeon: 'Abandoned Mineworks (NMD), Black Asylum (NMD), Broken Bulwark, Buried Halls, Calibel\'s Mine, Crumbling Hekma, Earthen Wound (NMD), Forbidden City, Guulrahn Slums (NMD), Halls of the Damned, Haunted Refuge, Immortal Emanation, Iron Hold, Lost Archives (NMD), Lost Keep, Maddux Watch, Mariner\'s Refuge, Oblivion, Onyx Hold (NMD), Penitent Cairns, Sealed Archives, Seaside Descent, Stockades, Sunken Ruins (NMD), Tomb of the Saints, Twisted Hollow, Whispering Vault (NMD), Akkhan\'s Grasp, Collapsed Vault, Dead Man\'s Dredge, Fetid Mausoleum, Forbidden City, Hallowed Ossuary, Heathen\'s keep, Immortal Emanation, Kor Dragan Barracks (NMD), Sanguine Chapel, Zenith (NMD)' },
    { name: 'Razorplate', type: 'Chest', monsters: 'Beast, Spiders', dungeon: 'Abandoned Mineworks (NMD), Black Asylum (NMD), Broken Bulwark, Buried Halls, Calibel\'s Mine, Crumbling Hekma, Earthen Wound (NMD), Forbidden City, Guulrahn Slums (NMD), Halls of the Damned, Haunted Refuge, Immortal Emanation, Iron Hold, Lost Archives (NMD), Lost Keep, Maddux Watch, Mariner\'s Refuge, Oblivion, Onyx Hold (NMD), Penitent Cairns, Sealed Archives, Seaside Descent, Stockades, Sunken Ruins (NMD), Tomb of the Saints, Twisted Hollow, Whispering Vault (NMD), Akkhan\'s Grasp, Collapsed Vault, Dead Man\'s Dredge, Fetid Mausoleum, Forbidden City, Hallowed Ossuary, Heathen\'s keep, Immortal Emanation, Kor Dragan Barracks (NMD), Sanguine Chapel, Zenith (NMD)' },
    { name: 'Asheara\'s Khanjar', type: 'Dagger', monsters: 'Bandits, Cultist', dungeon: 'Calibel\'s Mine, Faceless Shrine, Light\'s Watch, Luban\'s Rest, Maugan\'s Works, Maulwood (NMD), Mournfield, Raethwind Wilds, (NMD), Renegade\'s Retreat (NMD), Uldur\'s Cave, Buried Halls, Conclave (NMD), Cultist Refuge (NMD), Dark Ravine (NMD), Endless Gates, Faceless Shrine, Halls of the Damned, Heretics Asylum, Inferno, Leviathan\'s Maw, Path of the Blind, Steadfast Barracks, Serpent\'s Lair (NMD), Shadowed Plunge (NMD), Yashri\'s Sanctum' },
    { name: 'Condemnation', type: 'Dagger', monsters: 'Bandits, Cultist', dungeon: 'Calibel\'s Mine, Faceless Shrine, Light\'s Watch, Luban\'s Rest, Maugan\'s Works, Maulwood (NMD), Mournfield, Raethwind Wilds, (NMD), Renegade\'s Retreat (NMD), Uldur\'s Cave, Buried Halls, Conclave (NMD), Cultist Refuge (NMD), Dark Ravine (NMD), Endless Gates, Faceless Shrine, Halls of the Damned, Heretics Asylum, Inferno, Leviathan\'s Maw, Path of the Blind, Steadfast Barracks, Serpent\'s Lair (NMD), Shadowed Plunge (NMD), Yashri\'s Sanctum' },
    { name: 'Gohr\'s Devastating Grips', type: 'Gloves', monsters: 'Spiders', dungeon: 'Abandoned Mineworks (NMD), Blind Burrows (NMD), Champion\'s Demise (NMD), Defiled Catacomb, Deserted Underpass, Feral\'s Den (NMD), Guulran Canals (NMD), Hive Diablo, Oldstones, Pallid Delve, Sarat\'s Lair, Sirocco Caverns, Whispering Pines (NMD), Witchwater (NMD)' },
    { name: 'Howl from Below', type: 'Gloves', monsters: 'Spiders', dungeon: 'Abandoned Mineworks (NMD), Blind Burrows (NMD), Champion\'s Demise (NMD), Defiled Catacomb, Deserted Underpass, Feral\'s Den (NMD), Guulran Canals (NMD), Hive Diablo, Oldstones, Pallid Delve, Sarat\'s Lair, Sirocco Caverns, Whispering Pines (NMD), Witchwater (NMD)' },
    { name: 'Grasp of Shadow', type: 'Gloves', monsters: 'Spiders', dungeon: 'Abandoned Mineworks (NMD), Blind Burrows (NMD), Champion\'s Demise (NMD), Defiled Catacomb, Deserted Underpass, Feral\'s Den (NMD), Guulran Canals (NMD), Hive Diablo, Oldstones, Pallid Delve, Sarat\'s Lair, Sirocco Caverns, Whispering Pines (NMD), Witchwater (NMD)' },
    { name: 'Gloves of the Illuminator', type: 'Gloves', monsters: 'Spiders', dungeon: 'Abandoned Mineworks (NMD), Blind Burrows (NMD), Champion\'s Demise (NMD), Defiled Catacomb, Deserted Underpass, Feral\'s Den (NMD), Guulran Canals (NMD), Hive Diablo, Oldstones, Pallid Delve, Sarat\'s Lair, Sirocco Caverns, Whispering Pines (NMD), Witchwater (NMD)' },
    { name: 'Fist of Fate', type: 'Gloves', monsters: 'Spiders', dungeon: 'Abandoned Mineworks (NMD), Blind Burrows (NMD), Champion\'s Demise (NMD), Defiled Catacomb, Deserted Underpass, Feral\'s Den (NMD), Guulran Canals (NMD), Hive Diablo, Oldstones, Pallid Delve, Sarat\'s Lair, Sirocco Caverns, Whispering Pines (NMD), Witchwater (NMD)' },
    { name: 'Frostburn', type: 'Gloves', monsters: 'Spiders', dungeon: 'Abandoned Mineworks (NMD), Blind Burrows (NMD), Champion\'s Demise (NMD), Defiled Catacomb, Deserted Underpass, Feral\'s Den (NMD), Guulran Canals (NMD), Hive Diablo, Oldstones, Pallid Delve, Sarat\'s Lair, Sirocco Caverns, Whispering Pines (NMD), Witchwater (NMD)' },
    { name: 'Tempest Roar', type: 'Helmet', monsters: 'Cannibals, Cultist', dungeon: 'Bastion of Faith, Bloodsoaked Crag, Charnel House, Earthen Wound (NMD), Faceless Shrine, Guulrahn Slums (NMD), Pallid Delve, Steadfast Barracks, Buried Halls, Conclave (NMD), Cultist Refuge (NMD), Dark Ravine (NMD), Endless Gates, Faceless Shrine, Halls of the Damned, Heretics Asylum, Inferno, Leviathan\'s Maw, Path of the Blind, Steadfast Barracks, Serpent\'s Lair (NMD), Shadowed Plunge (NMD), Yashri\'s Sanctum' },
    { name: 'Vasily\'s Prayer', type: 'Helmet', monsters: 'Cannibals, Cultist', dungeon: 'Bastion of Faith, Bloodsoaked Crag, Charnel House, Earthen Wound (NMD), Faceless Shrine, Guulrahn Slums (NMD), Pallid Delve, Steadfast Barracks, Buried Halls, Conclave (NMD), Cultist Refuge (NMD), Dark Ravine (NMD), Endless Gates, Faceless Shrine, Halls of the Damned, Heretics Asylum, Inferno, Leviathan\'s Maw, Path of the Blind, Steadfast Barracks, Serpent\'s Lair (NMD), Shadowed Plunge (NMD), Yashri\'s Sanctum' },
    { name: 'Deathless Visage', type: 'Helmet', monsters: 'Cannibals, Cultist', dungeon: 'Bastion of Faith, Bloodsoaked Crag, Charnel House, Earthen Wound (NMD), Faceless Shrine, Guulrahn Slums (NMD), Pallid Delve, Steadfast Barracks, Buried Halls, Conclave (NMD), Cultist Refuge (NMD), Dark Ravine (NMD), Endless Gates, Faceless Shrine, Halls of the Damned, Heretics Asylum, Inferno, Leviathan\'s Maw, Path of the Blind, Steadfast Barracks, Serpent\'s Lair (NMD), Shadowed Plunge (NMD), Yashri\'s Sanctum' },
    { name: 'Cowl of the Nameless', type: 'Helmet', monsters: 'Cannibals, Cultist', dungeon: 'Bastion of Faith, Bloodsoaked Crag, Charnel House, Earthen Wound (NMD), Faceless Shrine, Guulrahn Slums (NMD), Pallid Delve, Steadfast Barracks, Buried Halls, Conclave (NMD), Cultist Refuge (NMD), Dark Ravine (NMD), Endless Gates, Faceless Shrine, Halls of the Damned, Heretics Asylum, Inferno, Leviathan\'s Maw, Path of the Blind, Steadfast Barracks, Serpent\'s Lair (NMD), Shadowed Plunge (NMD), Yashri\'s Sanctum' },
    { name: 'Andariel\'s Visage', type: 'Helmet', monsters: 'Cannibals, Cultist', dungeon: 'Bastion of Faith, Bloodsoaked Crag, Charnel House, Earthen Wound (NMD), Faceless Shrine, Guulrahn Slums (NMD), Pallid Delve, Steadfast Barracks, Buried Halls, Conclave (NMD), Cultist Refuge (NMD), Dark Ravine (NMD), Endless Gates, Faceless Shrine, Halls of the Damned, Heretics Asylum, Inferno, Leviathan\'s Maw, Path of the Blind, Steadfast Barracks, Serpent\'s Lair (NMD), Shadowed Plunge (NMD), Yashri\'s Sanctum' },
    { name: 'Harlequin Crest', type: 'Helmet', monsters: 'Cannibals, Cultist', dungeon: 'Bastion of Faith, Bloodsoaked Crag, Charnel House, Earthen Wound (NMD), Faceless Shrine, Guulrahn Slums (NMD), Pallid Delve, Steadfast Barracks, Buried Halls, Conclave (NMD), Cultist Refuge (NMD), Dark Ravine (NMD), Endless Gates, Faceless Shrine, Halls of the Damned, Heretics Asylum, Inferno, Leviathan\'s Maw, Path of the Blind, Steadfast Barracks, Serpent\'s Lair (NMD), Shadowed Plunge (NMD), Yashri\'s Sanctum' },
    { name: 'Storm\'s Companion', type: 'Pants', monsters: 'Drowned', dungeon: 'Akkhan\'s Grasp, Belfry Zakara, Corrupted Grotto, Dead Man\'s Dredge, Fetid Mausoleum, Flooded Depths, Ghoa Ruins, Haunted Refuge, Mariner\'s Refuge, Putrid Aquifer, Ruinds of Eridu, Sunken Library, Vault of the Forsaken.' },
    { name: 'Eyes in the Dark', type: 'Pants', monsters: 'Drowned', dungeon: 'Akkhan\'s Grasp, Belfry Zakara, Corrupted Grotto, Dead Man\'s Dredge, Fetid Mausoleum, Flooded Depths, Ghoa Ruins, Haunted Refuge, Mariner\'s Refuge, Putrid Aquifer, Ruinds of Eridu, Sunken Library, Vault of the Forsaken.' },
    { name: 'Iceheart Brais', type: 'Pants', monsters: 'Drowned', dungeon: 'Akkhan\'s Grasp, Belfry Zakara, Corrupted Grotto, Dead Man\'s Dredge, Fetid Mausoleum, Flooded Depths, Ghoa Ruins, Haunted Refuge, Mariner\'s Refuge, Putrid Aquifer, Ruinds of Eridu, Sunken Library, Vault of the Forsaken.' },
    { name: 'Temerity', type: 'Pants', monsters: 'Drowned', dungeon: 'Akkhan\'s Grasp, Belfry Zakara, Corrupted Grotto, Dead Man\'s Dredge, Fetid Mausoleum, Flooded Depths, Ghoa Ruins, Haunted Refuge, Mariner\'s Refuge, Putrid Aquifer, Ruinds of Eridu, Sunken Library, Vault of the Forsaken.' },
    { name: 'Hunter\'s Zenith', type: 'Ring', monsters: 'none', dungeon: 'none' },
    { name: 'Ring of Mendeln', type: 'Ring', monsters: 'none', dungeon: 'none' },
    { name: 'Mother\'s Embrace', type: 'Ring', monsters: 'none', dungeon: 'none' },
    { name: 'Ring of the Starless Skies', type: 'Ring', monsters: 'none', dungeon: 'none' },
    { name: 'Black River', type: '1H Scythe', monsters: 'Drowned', dungeon: 'Akkhan\'s Grasp, Belfry Zakara, Corrupted Grotto, Dead Man\'s Dredge, Fetid Mausoleum, Flooded Depths, Ghoa Ruins, Haunted Refuge, Mariner\'s Refuge, Putrid Aquifer, Ruinds of Eridu, Sunken Library, Vault of the Forsaken.' },
    { name: 'Bloodless Scream', type: '1H Scythe', monsters: 'Drowned', dungeon: 'Akkhan\'s Grasp, Belfry Zakara, Corrupted Grotto, Dead Man\'s Dredge, Fetid Mausoleum, Flooded Depths, Ghoa Ruins, Haunted Refuge, Mariner\'s Refuge, Putrid Aquifer, Ruinds of Eridu, Sunken Library, Vault of the Forsaken.' },
    { name: 'Greatstaff of the Crone', type: 'Staff', monsters: 'Fallen', dungeon: 'Ancient\'s Lament (NMD), Demon\'s Wake (NMD), Fading Echo, Grinning Labyrinth, Oblivion, Ruinds of Eridu, Wretched Delve' },
    { name: 'Staff of Endless Rage', type: 'Staff', monsters: 'Goatmen', dungeon: 'Anica\'s Claim, Broken Bulwark, Champion\'s Demise (NMD), Domhainne Tunnels, Forsaken Quarry, Hoarfrost Demise, Komdor Temple, Mercy\'s Reach, Oldstones, Rimescar Caverns, Sepulcher of the Forsworn, Shivta Ruins(NMD)' },
    { name: 'Staff of Lam Esen', type: 'Staff', monsters: 'Goatmen', dungeon: 'Anica\'s Claim, Broken Bulwark, Champion\'s Demise (NMD), Domhainne Tunnels, Forsaken Quarry, Hoarfrost Demise, Komdor Temple, Mercy\'s Reach, Oldstones, Rimescar Caverns, Sepulcher of the Forsworn, Shivta Ruins(NMD)' },
    { name: 'Fields of Crimson', type: '2H Sword', monsters: 'Spiders, Vampires', dungeon: 'Abandoned Mineworks (NMD), Blind Burrows (NMD), Champion\'s Demise (NMD), Defiled Catacomb, Deserted Underpass, Feral\'s Den (NMD), Guulran Canals (NMD), Hive Diablo, Oldstones, Pallid Delve, Sarat\'s Lair, Sirocco Caverns, Whispering Pines (NMD), Witchwater (NMD), Akkhan\'s Grasp, Collapsed Vault, Dead Man\'s Dredge, Fetid Mausoleum, Forbidden City, Hallowed Ossuary, Heathen\'s keep, Immortal Emanation, Kor Dragan Barracks (NMD), Sanguine Chapel, Zenith (NMD)' },
    { name: 'The Grandfather', type: '2H Sword', monsters: 'Spiders, Vampires', dungeon: 'Abandoned Mineworks (NMD), Blind Burrows (NMD), Champion\'s Demise (NMD), Defiled Catacomb, Deserted Underpass, Feral\'s Den (NMD), Guulran Canals (NMD), Hive Diablo, Oldstones, Pallid Delve, Sarat\'s Lair, Sirocco Caverns, Whispering Pines (NMD), Witchwater (NMD), Akkhan\'s Grasp, Collapsed Vault, Dead Man\'s Dredge, Fetid Mausoleum, Forbidden City, Hallowed Ossuary, Heathen\'s keep, Immortal Emanation, Kor Dragan Barracks (NMD), Sanguine Chapel, Zenith (NMD)' },
    { name: 'Ramaladni\'s Magnum Opus', type: '1H Sword', monsters: 'Beast, Skeleton, Snakes', dungeon: 'Akkhan\'s Grasp, Blind Burrows (NMD), Corrupted Grotto, Fetid Mausoleum, Haunted Refuge, Leviathan\'s Maw, Light\'s Refuge, Mournfield, Path of the Blind, Tomb of the Saints, Uldur\'s Cave, Ancient Reservoir, Belfry Zakara, Betrayer\'s Row, Black Asylum (NMD), Caldera Gate, Collapsed Vault, Crumbling Hekma, Crusader\'s Cathedral (NMD), Defiled Catacomb, Demon\'s Wake (NMD), Forgotten Depths, Forgotten Ruins, Garan Hold, Hakan\'s Refuge, Halls of the Damned, Hoarfrost Demise, Komdor Temple, Kor Dragan Barracks (NMD), Luban\'s Rest, Maddux Watch, Mournfield, Nostrava Deepwood, Pallid Delve, Seaside Descent, Stockades, Sunken Library, Tomernted Ruins, Underroot, Yshari\'s Sanctum, Zenith (NMD), Deserted Underpass, Forgotten Ruins, Ghoa Ruins, Hakan\'s Refuge, Putrid Aquifer, Serpent\'s Lair (NMD), Shadowed Plunge (NMD), Witchwater (NMD)' },
    { name: 'Doombringer', type: '1H Sword', monsters: 'Beast, Skeleton, Snakes', dungeon: 'Akkhan\'s Grasp, Blind Burrows (NMD), Corrupted Grotto, Fetid Mausoleum, Haunted Refuge, Leviathan\'s Maw, Light\'s Refuge, Mournfield, Path of the Blind, Tomb of the Saints, Uldur\'s Cave, Ancient Reservoir, Belfry Zakara, Betrayer\'s Row, Black Asylum (NMD), Caldera Gate, Collapsed Vault, Crumbling Hekma, Crusader\'s Cathedral (NMD), Defiled Catacomb, Demon\'s Wake (NMD), Forgotten Depths, Forgotten Ruins, Garan Hold, Hakan\'s Refuge, Halls of the Damned, Hoarfrost Demise, Komdor Temple, Kor Dragan Barracks (NMD), Luban\'s Rest, Maddux Watch, Mournfield, Nostrava Deepwood, Pallid Delve, Seaside Descent, Stockades, Sunken Library, Tomernted Ruins, Underroot, Yshari\'s Sanctum, Zenith (NMD), Deserted Underpass, Forgotten Ruins, Ghoa Ruins, Hakan\'s Refuge, Putrid Aquifer, Serpent\'s Lair (NMD), Shadowed Plunge (NMD), Witchwater (NMD)' },
    { name: 'Flamescar', type: 'Wand', monsters: 'Ghost, Vampires', dungeon: 'Abandoned Mineworks (NMD), Black Asylum (NMD), Broken Bulwark, Buried Halls, Calibel\'s Mine, Crumbling Hekma, Earthen Wound (NMD), Forbidden City, Guulrahn Slums (NMD), Halls of the Damned, Haunted Refuge, Immortal Emanation, Iron Hold, Lost Archives (NMD), Lost Keep, Maddux Watch, Mariner\'s Refuge, Oblivion, Onyx Hold (NMD), Penitent Cairns, Sealed Archives, Seaside Descent, Stockades, Sunken Ruins (NMD), Tomb of the Saints, Twisted Hollow, Whispering Vault (NMD), Akkhan\'s Grasp, Collapsed Vault, Dead Man\'s Dredge, Fetid Mausoleum, Forbidden City, Hallowed Ossuary, Heathen\'s keep, Immortal Emanation, Kor Dragan Barracks (NMD), Sanguine Chapel, Zenith (NMD)' },
    { name: 'Hellhammer', type: '2H Mace', monsters: 'Bandits, Drowned', dungeon: 'Calibel\'s Mine, Faceless Shrine, Light\'s Watch, Luban\'s Rest, Maugan\'s Works, Maulwood (NMD), Mournfield, Raethwind Wilds, (NMD), Renegade\'s Retreat (NMD), Uldur\'s Cave, Akkhan\'s Grasp, Belfry Zakara, Corrupted Grotto, Dead Man\'s Dredge, Fetid Mausoleum, Flooded Depths, Ghoa Ruins, Haunted Refuge, Mariner\'s Refuge, Putrid Aquifer, Ruinds of Eridu, Sunken Library, Vault of the Forsaken.' },
    { name: 'Overkill', type: '2H Mace', monsters: 'Bandits, Drowned', dungeon: 'Calibel\'s Mine, Faceless Shrine, Light\'s Watch, Luban\'s Rest, Maugan\'s Works, Maulwood (NMD), Mournfield, Raethwind Wilds, (NMD), Renegade\'s Retreat (NMD), Uldur\'s Cave, Akkhan\'s Grasp, Belfry Zakara, Corrupted Grotto, Dead Man\'s Dredge, Fetid Mausoleum, Flooded Depths, Ghoa Ruins, Haunted Refuge, Mariner\'s Refuge, Putrid Aquifer, Ruinds of Eridu, Sunken Library, Vault of the Forsaken.' },
  // ... Add the rest of the item data here ...
];

const ItemSelector = () => {
  const [selectedItem, setSelectedItem] = useState(itemsData[0]);

  const handleItemChange = (event) => {
    const selectedItemName = event.target.value;
    const selected = itemsData.find(item => item.name === selectedItemName);
    setSelectedItem(selected);
  };

  return (
    <div>
      <label htmlFor="itemSelect">Select an item:</label>
      <select id="itemSelect" onChange={handleItemChange} value={selectedItem.name}>
        {itemsData.map((item) => (
          <option key={item.name} value={item.name}>{item.name}</option>
        ))}
      </select>

      <h2>Selected Item:</h2>
      <p>Name: {selectedItem.name}</p>
      <p>Type: {selectedItem.type}</p>
      <p>Monsters: {selectedItem.monsters}</p>
      <p>Dungeon Location: {selectedItem.dungeon}</p>
    </div>
  );
};

export default ItemSelector;
